CREATE USER 'enquesta'@'%' IDENTIFIED WITH mysql_native_password AS 'enquesta';GRANT USAGE ON *.* TO 'enquesta'@'%' REQUIRE NONE WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;
CREATE DATABASE IF NOT EXISTS `enquesta`;GRANT ALL PRIVILEGES ON `enquesta`.* TO 'enquesta'@'%';
